
services:
  app:
    build:
      context: .
    container_name: nest_app
    command: npm run start:dev  # Start in watch mode
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - .:/app                   
      - /app/node_modules         
    develop:
      watch:
        - action: sync          
          path: ./src            
          target: /app/src         
        - action: rebuild
          path: package.json       
          target: /app/package.json
      ignore:
          - node_modules/

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: irakli # these variables can also come from .env
      POSTGRES_PASSWORD: A11qitshors
      POSTGRES_DB: your_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: