version: '3.8'

services:
  database:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lavapi_network

  app:
    build:
      context: .
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
    volumes:
      - .:/app
    networks:
      - lavapi_network

volumes:
  postgres_data:

networks:
  lavapi_network: